name: Unit tests
on: [push, pull_request]
jobs:
  run:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python  
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Static code checking with pyflakes
      run: |
        pip install pyflakes
        pyflakes mkversion
    - name: Run unit tests
      run: |
        pip install -e .
        # Not run currently
        # python -m unittest tests/test_entry.py